language: rust
rust:
- stable
- beta
- nightly
sudo: false

deploy:
  provider: script
  script: "cargo publish --token=$CARGO_TOKEN --verbose"
  env:
  - secure: "Cz4PJRFJiRy33wpFZ+dWB2vbZYvCMmR2A3KbY5LlAI+CQgf+VEhPnVcP3RDlSZy/qChqJg2XWQDDjaXDmHEGXoSt4WZBPPRVTRrbwN1jm2uMhiXKj45PYC8GyziKkF0PrGZK0NpSO/JgmunKBp0+kxqEOl0x9a6Yo4LRCkSp69IIdfKAo7kvjuR9F+Tit9yHW+LZMqwNaldQtItl7ZANCzUqBD3r23j9bUBd64hNRZMxJD36/S4Eua3isnQN5fLI/o0trPaA0WxhsxAWNyaVWSc1NRvIIL2LZ0kWuL3D05qUQiA4mnjGhLgpovNJLWIG9+d7jaLa0mOHeBY0vCcd2klRWDZtl4Xi8gAuZRDEkEO2JnOnBNXK2HWdX4R5SCRM6y8LDZQqQ3ab1shT5+Jhi8ztkEEqWThCDKJ4358ocWCnyOdPk2S/JzQV18/OT9EDv2H4gRMylzJ8ffpn//5MiB1NZZI5QrpLbtXxXMPACohHc2AVTVtsnJ6OfZuG6FYoWkKIx4iHLV0su06j4j7lY8+/yV+ljulMNNUNkidQmgdb3WxS1LQEIcNpCJG9LS4JfLhje4Q1YO3ttMfvO39vrmZC0z8g4ePo+fpfctfx3AyUrfSyBmWf3xFm146yWimWIiPzX5GOSK9n+xxbUztbbjnHGl8VEUjGZZkxMkDJ+IM="
  on:
    rust: stable
    tags: true
